### ISSUE TITLE
defaultProps Deprecation

### ISSUE THREAD

**Issue by leafkrober** [gilbarbara/react-floater#107]
## 🐛 Bug Report

Console errors when using react-floater

`Warning: ReactFloater: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

![image](https://github.com/gilbarbara/react-floater/assets/159051096/6764ef2c-6baa-424b-b743-a19f803a62f2)

## To Reproduce

Render a floater and observe the console (note: this may only appear on react 18+)

## Expected behavior

No console errors or messages about defaultProps deprecation

## Run `npx envinfo --system --binaries --npmPackages react-floater`

```bash
  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.17 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 9.1.1 - ~/.nvm/versions/node/v20.13.1/bin/pnpm
    bun: 1.1.12 - /opt/homebrew/bin/bun
```

**Comment by gilbarbara** [comment]
Hey @leafkrober 

Which react version are you using?

**Comment by reergymerej** [comment]
same - react@18.3
