### ISSUE TITLE
click outside to close the floater

### ISSUE THREAD

**Issue by hjfrun** [gilbarbara/react-floater#34]
How to close the floater by click outside?

<img width="629" alt="wx20180517-204016 2x" src="https://user-images.githubusercontent.com/4508489/40177958-ab7b86e2-5a12-11e8-8246-f4e77a1ff2b9.png">

Our site may have many floaters in one page. The floater pops by ` click` event, will be only closed by click the anchor button(i here) or the `X` button.  That was very ugly, could you please give me some advice to implement the functionality.

**Comment by gilbarbara** [comment]
You could wrap the floater with a controlled state using the `open` prop and rendering an Overlay. Check out the WithOverlay component in the [demo](https://codesandbox.io/s/84vn36m178)

**Comment by paigeflourin** [comment]
Hi @gilbarbara ,

i am using typescript and I cannot use proptypes with it. how do i close the floater when i click outside?
