### ISSUE TITLE
Generate React warning

### ISSUE THREAD

**Issue by marcoancona** [gilbarbara/react-floater#36]
>Expected behavior
No warning

>Actual behavior
<img width="429" alt="screen shot 2018-07-08 at 16 19 49" src="https://user-images.githubusercontent.com/2278117/42420753-d67a8eca-82ca-11e8-9bbf-032a57ca02c1.png">

>Steps to reproduce the problem
Just load a Floater component

>React version
15.4.2

>React-Tooltips version
3.6.1

**Comment by gilbarbara** [comment]
It's an error in your code. 
`in div (created by Topbar)`
