### ISSUE TITLE
Allow user to manually set the offset of the arrow

### ISSUE THREAD

**Issue by mrstebo** [gilbarbara/react-floater#37]
I've been using this library indirectly for an Electron app (with [react-joyride](https://github.com/gilbarbara/react-joyride)), and found the need to be able to move the arrow. This is because I wanted the arrow to point to something outside of the application window.

Use cases for others may be that they create a dialog and want a step to point to it from a parent window.

**Comment by gilbarbara** [comment]
Hello,
The floater, including the arrow positioning, is handled by [popper.js](https://popper.js.org/popper-documentation.html#modifiers..arrow).
If you need to change its behavior, you could set a modifier function via props.
Take a look at the [source](https://github.com/gilbarbara/react-floater/blob/ea11ab22c9ceff1904f25d0b35b5162641b6044a/src/components/index.js#L212)
