### ISSUE TITLE
Provide a way to delay opening of the Floater

### ISSUE THREAD

**Issue by mrstebo** [gilbarbara/react-floater#39]
When using this library for tooltip components, I would like to be able to delay making the Floater visible. This is so that it replicates the behaviour of tooltips you'd normally find on desktop applications.

**Comment by gilbarbara** [comment]
You can create a wrapper component to use the floater in a controlled mode with `open` prop, so you can delay the trigger.
Check out the controlled tooltip code in the [demo](https://codesandbox.io/s/84vn36m178).
