### ISSUE TITLE
ReactFloater erros on tour stop

### ISSUE THREAD

**Issue by sarates** [gilbarbara/react-floater#46]
>Expected behavior

Tour stops, I make some operations, tour run 

>Actual behavior

Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ReactFloater component.

>Steps to reproduce the problem

    if ([EVENTS.STEP_BEFORE].includes(type) && !this.checkVisible(htmlTarget)) {
      this.setState({
        run : false,
        tutorialLoading: true
      }, () => {
        this.setState({
          run : true,
          stepIndex : 8
        });
      });
    }

>React version

    "react": "^15.5.4",

>React-Joyride version

    "react-joyride": "^2.0.0-10",

>Error stack

*If you are having UI issues, make sure to send a public URL or codesandbox example.*

**Comment by gilbarbara** [comment]
This will be handled in #45
