### ISSUE TITLE
Do not render the floater content before the floater is opened

### ISSUE THREAD

**Issue by tarjei** [gilbarbara/react-floater#48]
## 🚀 Feature Idea

When using the component render function the function should not be called before the floater needs to be opened.

## Motivation
I got a series of places to use the floater and rendering all the floaters at once delays the rendering of the whole component. 

When I render I see all the render functions called at once.

## Example
See motivation.

**Comment by gilbarbara** [comment]
Feel free to submit a PR

**Comment by gilbarbara** [comment]
Fixed in 0.8.0
