### ISSUE TITLE
Mildly controlled floaters

### ISSUE THREAD

**Issue by tarjei** [gilbarbara/react-floater#49]
## 🚀 Feature Idea

It should be possible for the target to trigger a float that will only be closed by the closeFn.

## Motivation

If a floater has a lot of content, then we want it to stay up even when the users mouse has moved - esp if the target is small. Then it should be possible to pass a open callback to the target that when clicked triggers the floater and lets it stay up for longer.

## Example

```react

<Floater content={
   (closeFloater)=> <div>
           <button onClick={closeFloater.closeFn}>Close</Button>
            <p>Some content</p></div> }
>
      {(open) => <button onClick={open}> Trigger me!</button>}
</Floater>

```

**Comment by gilbarbara** [comment]
Hey,

You have three options:
- Change the `event` to `click` so it can be controlled with the `closeFn`
- Leave it as `hover` and increase the `eventDelay`
- Make in controllable using the `open` prop and use your own state to handle it.

I have added the controlled mode exactly for these kind of situations.

**Comment by gilbarbara** [comment]
But in terms of UX a tooltip should have a short text. If you need to display a lot of text a dialog should be used instead.

**Comment by tarjei** [comment]
@gilbarbara good point sorry for not answering then!
