### ISSUE TITLE
Floater ignores rapid changes in 'open' prop

### ISSUE THREAD

**Issue by dropbeardan** [gilbarbara/react-floater#55]
## 🐛 Bug Report

When rapidly changing the `open` prop, i.e. toggling the Floater when it is opening/closing, the Floater will ignore the change in prop.

## To Reproduce

1) Make a floater attach to a button controlled by the open prop
2) Double-Click the target button to open it and close it while it is still opening

## Expected behavior

The target button should be closed after the second click, especially since the Floater accepts the prop state of `open: false` despite not being closed (since it maintains its own internal state of opened/closed).

**Comment by gilbarbara** [comment]
Fixed in 0.8.0
