### ISSUE TITLE
react-floater overlay problem if container have overflow : auto

### ISSUE THREAD

**Issue by gabrielsdimeli** [gilbarbara/react-floater#58]
## 🐛 Bug Report

I have my overlay component inside of a table with overflow auto for responsive but if overflow is activated then the overlay lose reference of the position of the target.

## To Reproduce

Just create a div container with overflow : auto, 

## Expected behavior

Don't lose reference of the position of the target setted.

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/clever-river-32mtq

**Comment by gilbarbara** [comment]
Hey,

I'm trying to understand why one would set `overflow` in an element without height. Your codesandbox isn't a real use case, so I really can't see what's wrong...

Anyway, this library uses `popper.js` for positioning so there's not much I can do.
Take a look in their [issues](https://github.com/FezVrasta/popper.js/search?q=overflow+is%3Aissue&type=Issues) to see if there's a workaround or something.

**Comment by gilbarbara** [comment]
Anyway, you can pass popper.js options to this component, maybe there's one that can help with your case?
Check their [examples](https://popper.js.org/) for more info.
