### ISSUE TITLE
Possibility to round the arrow or provide SVG for it

### ISSUE THREAD

**Issue by clementdevos** [gilbarbara/react-floater#60]
## 🚀 Feature Idea

Hi there, we're already using a popper card in our app but the arrow is not a triangle, and we'd like to override react-joyride tooltip arrow (so the arrow of react-floater)

## Motivation

Unify the arrow looks of the Tooltips in our app

## Example

this is our arrow
![image](https://user-images.githubusercontent.com/5870982/67865937-74e5ed80-fb28-11e9-95a2-067557323fb5.png)

Any idea how we could do that ? The code looks like it's drawing polygons!

**Comment by gilbarbara** [comment]
Hello,
There's no way to change the curvature of the arrow and this level of customization isn't something I plan to work on.
Feel free to submit a PR.

**Comment by clementdevos** [comment]
Thanks for your reply!
