### ISSUE TITLE
Arrow is misplace in IE 11

### ISSUE THREAD

**Issue by jucallej** [gilbarbara/react-floater#63]
## 🐛 Bug Report

The left arrow is misplaced on IE 11

## To Reproduce

Run the demo app https://github.com/gilbarbara/react-floater-demo on IE 11 and see that the left arrow is misplaced

![Not_working_VirtualBox_IE11 - Win7_22_11_2019_11_14_44](https://user-images.githubusercontent.com/4417038/69422829-9e0b2f80-0d1c-11ea-8d5f-19730c478569.png)

## Expected behavior

The arrow should not be misplaced.

**Comment by jucallej** [comment]
This is releated to https://github.com/gilbarbara/react-joyride/issues/517. I'm happy to look into making a PR for this 😀

**Comment by gilbarbara** [comment]
@jucallej I'm thinking of dropping support for IE.
I can't see a way to support it without hacks and that's not something worth the trouble.

**Comment by jucallej** [comment]
@gilbarbara Just saw the comment. I understand whatever you decide 😀. In this case it's a css change (https://github.com/jucallej/react-floater/commit/fab103600cecafe14ceb4623dde7bf5e0d1af1a5). Everything else seems to work properly on IE 11 😁 (in my case I need to support it on my company and is afecting https://github.com/gilbarbara/react-joyride/issues/517 otherwise that ticket can not be cleanly solved). Should I open the PR for this? Your choice 😉

**Comment by jucallej** [comment]
Hey @gilbarbara ! What are your thoughts on this? Sorry for chasing you 😀

**Comment by gilbarbara** [comment]
@jucallej Sure, it's a simple fix.
