### ISSUE TITLE
If the Floater is on the left, the arrow will cover content 

### ISSUE THREAD

**Issue by yuxuan** [gilbarbara/react-floater#65]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/2955214/70768819-e5c42a80-1da1-11ea-946a-c266c8de3058.png)

The "You shall not click me" link is not able to click. The reason is arrow width is 100% which covers the content part, due to this fix https://github.com/gilbarbara/react-floater/commit/f1c44752a5cdecc83aea6f792ee5c6c770ca0533

## To Reproduce

https://codesandbox.io/s/brave-perlman-e7d4o 
Make "Right" floater appears on left side

**Comment by gilbarbara** [comment]
Sorry about that!

It's fixed in v0.7.2
