### ISSUE TITLE
Can we upgrade to use popperjs/core@2.0.6 which has 40% less bundle size than popper 1.16.1

### ISSUE THREAD

**Issue by GoChartingAdmin** [gilbarbara/react-floater#66]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [The README documentation](https://github.com/gilbarbara/react-floater/blob/master/README.md)
- [The Reactiflux #library channel on discord](https://discord.gg/W7yyNU)
- The [react-floater](https://stackoverflow.com/questions/tagged/react-floater) tag on [StackOverflow](https://stackoverflow.com/questions/ask)

**Comment by gilbarbara** [comment]
sure, feel free to submit a PR

**Comment by gilbarbara** [comment]
It's updated in react-floater@next

**Comment by gilbarbara** [comment]
Fixed in 0.8.0
