### ISSUE TITLE
Floater will not close when hover control is clicked (iPad, iOS 13, Safari)

### ISSUE THREAD

**Issue by nealhen** [gilbarbara/react-floater#70]
## 🐛 Bug Report

Using Safari on an iPad, the "convert hover to click" will open the floater but will not close it.

## To Reproduce

Open https://d0pt7.csb.app in Safari on an iPadAir 2, iOS version 13.3.1. **Note:** This does not appear to be an issue on iOS 12. Click on any of the buttons in the hover section of the page, the floater will show. Click on the same button again and the floater will not close.

## Expected behavior

The floater should hide once the button is clicked for a second time

```bash
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 1.12 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
```

**Comment by gilbarbara** [comment]
I don't have a device to test this.
Feel free to submit a PR
