### ISSUE TITLE
Placement  Center with Spotlight

### ISSUE THREAD

**Issue by afrancht** [gilbarbara/react-floater#73]
## 🚀 Feature Idea

It would be great to be able to put a label in the `center` of a `spotlight`.

## Motivation

It would look cleaner and not scroll when highlighting big components

## Example
Would be great of instead of this. The `label` with the info would appear in the middle of the spotlight! I know offsetting is a solution, but will cause a lot of trouble in different size displays.
![image](https://user-images.githubusercontent.com/19917183/87559270-5de92a80-c6ba-11ea-915c-9ffa57ef80d2.png)

Please provide an example of how this feature would be used.

**Comment by gilbarbara** [comment]
Hey

I'm not sure what you mean by "It would be great to be able to put a label in the center of a spotlight." 

Did you try using placement `center`?

**Comment by gilbarbara** [comment]
Isn't this is issue for react-joyride instead?
