### ISSUE TITLE
Joyride automatically starts when using center

### ISSUE THREAD

**Issue by tal87** [gilbarbara/react-floater#76]
## 🐛 Bug Report

I would like the first joyride step to be at the center of the attached element.
Whenever I do that, I don't see beacon but rather the open tooltip.

## To Reproduce

add placement: "center" to the first step of joyride.

## Expected behavior

I expect to see the beacon in the center of the element when I open the page and not the open tooltip.

**Comment by gilbarbara** [comment]
This issue is in the wrong repo...
Anyway, centered steps don't have beacons by design, it's not a bug.
