### ISSUE TITLE
Upgrade of peerdependencies to include react 17.0.0 

### ISSUE THREAD

**Issue by Redirts** [gilbarbara/react-floater#81]
## 🚀 Feature Idea

I am running a project with react 17.0.1 and this seems to work fine so I would like to suggest updating the peerdependencies to include react 17.0.0.

I see there is already a PR created for it;
https://github.com/gilbarbara/react-floater/pull/80

Thanks

**Comment by gilbarbara** [comment]
hey @Redirts 

As you said there's already a PR open for this...
And this is not a feature at all.

**Comment by Redirts** [comment]
Well, its not a bug either :-)
