### ISSUE TITLE
Vite fails to build/run because of "global is not defined"

### ISSUE THREAD

**Issue by wuifdesign** [gilbarbara/react-floater#83]
## 🐛 Bug Report

`Uncaught ReferenceError: global is not defined` when running dev mode with https://vitejs.dev/.
For the build i may use the solution from https://github.com/gilbarbara/react-floater/issues/75

I also get the error `Cannot call a namespace ('equal')` during build, but i can't finde out if it is related to react-floater or react-joyride. 

## To Reproduce

1. Create a new project with https://vitejs.dev/
2. Try to use https://github.com/gilbarbara/react-joyride (which depends on react-floater)

## Expected behavior

Should run/build

**Comment by Pernick** [comment]
I am getting both of those error with Vite app. Have you had any progress with it? I will dig around a bit and report back if I find something useful.

**Comment by Pernick** [comment]
Hello, I created a repo, where I tested this.

**`react-floater@latest`** - https://github.com/Pernick/react-floater-global-not-defined/tree/floater-latest
- `global is not defined` error is seen here

**`react-floater@next`** - https://github.com/Pernick/react-floater-global-not-defined/tree/floater-next
- `global is not defined` no longer her
- `equal3 is not a function` error is new here

I am unfortunately busy right now with different task, so I put this in a background for a bit, but hopefully I can get to it this evening.

**Comment by RaitoBezarius** [comment]
Just ran into this issue, too. I tried to enable various polyfills without any success with Vite.

**Comment by gilbarbara** [comment]
Fixed in 0.8.0

**Comment by JimmyRowland** [comment]
In 0.8.0 I am getting `equal3 is not a function`

**Comment by genk1** [comment]
Getting same problem in 0.8.0 `Uncaught TypeError: equal3 is not a function`

**Comment by NUKSI911** [comment]
Getting same problem in 0.8.0 Uncaught TypeError: equal3 is not a function

**Comment by gilbarbara** [comment]
This is issue was about the `global` variable...
