### ISSUE TITLE
Setting z-index and background color causes the floater to appear behind it - v0.8.0

### ISSUE THREAD

**Issue by chneil** [gilbarbara/react-floater#85]
## 🐛 Bug Report
A div that has both the z-index and a background color set, causes the floater to appears behind the div.

## To Reproduce
Setting z-index with background color - causes the floater to appear behind
Setting z-index without background color - works as expected
No z-index no background color - works as expected
No z-index with background color - works as expected

## Expected behavior
div with shadow, z-index and background color should not cause the floater to appear behind it

## Link to repl or repo (highly encouraged)
Example with a few different display type, z-index set, and background color
https://codesandbox.io/s/trusting-mayer-ut882y?file=/src/index.css

**Comment by gilbarbara** [comment]
Fixed in 0.8.1
Thanks
