### ISSUE TITLE
portalElement not working

### ISSUE THREAD

**Issue by NT-RX0** [gilbarbara/react-floater#95]
## 🐛 Bug Report

`portalElement` doesn't work

## To Reproduce

1. use demo in codesandbox
2. set portalElement and id to any <Block>
3. open sandbox in new tab, inspect element hierarchy

## Expected behavior

react-floater placed under the targeted dom

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/interesting-gates-5v1lv2?file=/src/App.tsx

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash
 System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 253.24 MB / 32.00 GB
    Shell: 3.4.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.13.2 - ~/.nvm/versions/node/v16.14.2/bin/npm
  npmPackages:
    react-floater: ^0.8.2 => 0.8.2
```

p.s. using pnpm v7.11

**Comment by gilbarbara** [comment]
Hey @NT-RX0 
Are you still having problems?
The link for the codesandbox doesn't exist anymore.
