### ISSUE TITLE
Demo Sandbox Broken

### ISSUE THREAD

**Issue by JLongley** [gilbarbara/react-floater#97]
## 🐛 Bug Report

The demo sandbox (https://codesandbox.io/s/github/gilbarbara/react-floater/tree/main/demo) fails to render with this error:
DependencyNotFoundError
Could not find dependency: 'prop-types' relative to '/node_modules/@gilbarbara/react-dropdown/lib/index.js'

## To Reproduce

Load sandbox https://codesandbox.io/s/github/gilbarbara/react-floater/tree/main/demo

## Expected behavior

A working demo

## Link to repl or repo (highly encouraged)

Please provide a https://codesandbox.io/ demo or similar.  
You can use this [template](https://codesandbox.io/s/github/gilbarbara/react-floater/tree/main/demo).

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash

```

**Comment by gilbarbara** [comment]
Fixed!
Thanks for the report.
